{% set name = "xh" %}
{% set version = "0.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ducaale/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 72f4d5e24165d8749433167e3ad3df8f26faafb250f1232acbe5192843e4157c

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - xh --help

about:
  home: https://github.com/ducaale/xh
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Friendly and fast tool for sending HTTP requests
  dev_url: https://github.com/ducaale/xh

extra:
  recipe-maintainers:
    - danielnachun
