context:
  version: "0.26.2"

package:
  name: xh
  version: ${{ version }}

source:
  url: https://github.com/ducaale/xh/archive/v${{ version }}.tar.gz
  sha256: 61a88a5b3beac225b75a11d6ed32659af78db7ff29c825def0ab7f4a2906cbd7

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - xh --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Friendly and fast tool for sending HTTP requests
  homepage: https://github.com/ducaale/xh
  repository: https://github.com/ducaale/xh

extra:
  recipe-maintainers:
    - danielnachun
