context:
  version: "0.24.0"

package:
  name: xh
  version: ${{ version }}

source:
  url: https://github.com/ducaale/xh/archive/v${{ version }}.tar.gz
  sha256: 80ecef9ca262b5564a951f41e11cf6125e5c4a62e66b87b071f6a333b6f40e5a

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - xh --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Friendly and fast tool for sending HTTP requests
  homepage: https://github.com/ducaale/xh
  repository: https://github.com/ducaale/xh

extra:
  recipe-maintainers:
    - danielnachun
